apiVersion: 1

datasources:
  - name: InfluxDB SafeGuard
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: safeguard
      defaultBucket: sensors
      tlsSkipVerify: true
    secureJsonData:
      token: safeguard-token-2026
    editable: true
